function create3dfigure(xdata1, ydata1, zdata1)
%CREATEFIGURE(xdata1, ydata1, zdata1)
%  XDATA1:  surface xdata
%  YDATA1:  surface ydata
%  ZDATA1:  surface zdata

%  Auto-generated by MATLAB on 29-Jan-2018 19:20:34

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1);
hold(axes1,'on');

% Create surf
surf(xdata1,ydata1,zdata1,'Parent',axes1,'DisplayName','data1');

% Create zlabel
zlabel('Load');

% Create ylabel
ylabel('Date');

% Create xlabel
xlabel('Time');

view(axes1,[-37.5 30]);
grid(axes1,'on');
